# Copyright 2021 The Knative Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Update Go Deps and Codegen"
description: "Updates golang dependencies and codegen using using hack/update-deps.sh and hack/update-codegen.sh"
branding:
  icon: download-cloud
  color: green
inputs:
  release:
    description: "Release? (vX.Y) defaults to current release"
  module-release:
    description: "Go module release version (vX.Y), defaults to current release"
  pr-empty-deps:
    description: "If true, send update PRs even for deps changes that don't change vendor. Defaults to false to reduce no-op PR spam."
outputs:
  log:
    description: "Report on module changes"
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    # *******************************************
    # CHANGE THIS LINE AFTER RELEASE
    # This should point to the _upcoming_ release
    # *******************************************
    RELEASE: ${{ inputs.release || 'v1.5' }}
    MODULE_RELEASE: ${{ inputs.module-release || 'v0.32' }}
    FORCE_DEPS: ${{ inputs.pr-empty-deps }}
