# TODO(mattmoor): https://github.com/golang/go/issues/29044
# apiVersion: build.knative.dev/v1alpha1
# kind: Build
# metadata:
#   generateName: goimports-ggcr
# spec:
#   source:
#     git:
#       url: https://github.com/google/go-containerregistry.git
#       revision: master
#   template:
#     name: goimports
#     arguments:
#     - name: ORGANIZATION
#       value: google
#     - name: REPOSITORY
#       value: go-containerregistry
