kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: periodic-build
rules:
  - apiGroups: ["build.knative.dev"]
    resources: ["builds"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: periodic-builder
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: periodic-build
subjects:
  - kind: ServiceAccount
    name: periodic-builder
roleRef:
  kind: Role
  name: periodic-build
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: periodic
spec:
  # Run on weekdays as 6am PST (2pm UTC)
  schedule: "00 14 * * 1-5"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccountName: periodic-builder
          containers:
          - name: periodic
            image: github.com/mattmoor/knobots/cmd/periodic
          restartPolicy: Never
      backoffLimit: 0
