apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: todo-subscription
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: githubchannel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: todo-bot
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: todo-bot
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: github.com/mattmoor/knobots/cmd/todo
            env:
            - name: GITHUB_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-comment-secret
                  key: accessToken
