apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: github-is-off-cluster
spec:
  hosts:
  - github.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
