# Copyright 2021 The Knative Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Update actions"
description: "Update GitHub actions"
branding:
  icon: refresh-ccw
  color: green
inputs:
  organization:
    description: 'The organization that the actions should be copied for.'
  repo:
    description: 'The repo being copied to, for repo-specific customizations.'
outputs:
  create_pr:
    description: "Whether a PR should be created because there were meaningful changes"
  log:
    description: "Log of changes"
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ORGANIZATION: ${{inputs.organization}}
    REPO: ${{inputs.repo}}
